parameters:
#    curso_core.example.class: Curso\CoreBundle\Example

services:
#    curso_core.example:
#        class: %curso_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
